name: Build SchemeConverter

on:
  push:
    paths:
    - "WormsSchemeConverter/**"
    - "Schemes/**"

jobs:
  build-scheme-converter:
    name: Build Scheme Converter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: cd WormsSchemeConverter && dotnet build --configuration Release
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: SchemeConverter
        path: WormsSchemeConverter/WormsScheme/bin/Release/netcoreapp2.2/
        
  create-wscs:
    name: Create .wsc files
    needs: build-scheme-converter
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Create output directory
      run: mkdir -p Schemes/release/
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Download build
      uses: actions/download-artifact@v1
      with:	
        name: SchemeConverter
    - name: Build
      run: cd Schemes; ./.build/build.ps1
    - name: Upload .wsc files
      uses: actions/upload-artifact@v1
      with:
        name: RGSchemes
        path: Schemes/release/

  release:
    name: Create GitHub Release for .wsc files
    needs: create-wscs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download .wscs
      uses: actions/download-artifact@v1
      with:
        name: RGSchemes
    - name: Release
      run: ./Schemes/.build/release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} RGSchemes
