name: "Code - Scanning"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '38 13 * * 6'

permissions:
  security-events: write

jobs:
  roslyn:
    name: Roysln
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run Inspections
        run: |
          mkdir -p sarif
          dotnet build Worms.sln /p:Sarif=true
          dotnet tool install --local Sarif.Multitool
          dotnet sarif merge sarif/*.sarif --recurse true --merge-runs --output-file=roslyn.sarif

      - name: Upload Rosyln SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: roslyn.sarif

  jetbrains:
    name: Jetbrains
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run Inspections
        run: |
          dotnet tool install --local JetBrains.ReSharper.GlobalTools
          dotnet jb inspectcode Worms.sln --output=jetbrains.sarif --format=sarif

      - name: Upload JetBrains SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: jetbrains.sarif

  codeql-actions:
    name: CodeQL (actions)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: actions
        build-mode: none

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:actions"

  codeql-csharp:
    name: CodeQL (csharp)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: csharp
        build-mode: manual

    - name: Build (csharp)
      run: dotnet build Worms.sln

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:csharp"
