name: ZZ - Inspections
permissions:
  contents: read
  pull-requests: write
  security-events: write

on:
  workflow_call:

jobs:
  inspections:
    name: Inspections
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run Inspections
        run: make inspections

      - name: Install SARIF Multitool
        if: always()
        run: dotnet tool install --global Sarif.Multitool

      - name: Upgrade SARIF to 2.1.0
        if: always()
        run: sarif rewrite '.output/roslyn.sarif' --output '.output/roslyn-2.1.0.sarif' --sarif-output-version Current

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: .output/roslyn-2.1.0.sarif

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: roslyn-sarif
          path: |
           .output/roslyn-2.1.0.sarif
           .output/roslyn.sarif
