name: ZZ - Inspections
permissions:
  contents: read
  pull-requests: write
  security-events: write

on:
  workflow_call:

jobs:
  inspections:
    name: Inspections
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Run Inspections
        run: make inspections

      - name: Upload Rosyln SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: roslyn.sarif

      - name: Upload JetBrains SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: jetbrains.sarif

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: code-inspections-roslyn
          path: |
           sarif/*
           roslyn.sarif
           jetbrains.sarif
